export const PRESET_TECHNICAL_SKILLS = [
  // Programming Languages
  'Python',
  'Java',
  'C++',
  'C',
  'JavaScript',
  'TypeScript',
  'Go',
  'Rust',
  'Kotlin',
  'Swift',
  'SQL',
  'PHP',
  'C#',
  // Web & Full-Stack
  'React.js',
  'Next.js',
  'Node.js',
  'Express.js',
  'Tailwind CSS',
  'HTML5 / CSS3',
  'Vue.js',
  'Angular',
  'Django',
  'FastAPI',
  'Spring Boot',
  'GraphQL',
  'REST APIs',
  // CS Fundamentals
  'Data Structures',
  'Algorithms',
  'Object-Oriented Programming (OOP)',
  'System Design',
  'Database Management (DBMS)',
  'Computer Networks',
  'Operating Systems',
  // Cloud, DevOps & Databases
  'PostgreSQL',
  'MongoDB',
  'MySQL',
  'Redis',
  'Docker',
  'Kubernetes',
  'Git & GitHub',
  'Linux / Bash',
  'AWS (Amazon Web Services)',
  'Microsoft Azure',
  'Google Cloud Platform (GCP)',
  'CI/CD Pipelines',
  // AI, ML & Data
  'Machine Learning',
  'Deep Learning',
  'Artificial Intelligence',
  'Natural Language Processing (NLP)',
  'Computer Vision',
  'Pandas & NumPy',
  'PyTorch',
  'TensorFlow',
  'Data Analytics',
];

export const PRESET_NON_TECHNICAL_SKILLS = [
  // Communication
  'Verbal Communication',
  'Written Communication',
  'Active Listening',
  'Presentation Skills',
  'Technical Documentation',
  'Public Speaking',
  // Leadership & Teamwork
  'Team Leadership',
  'Cross-Functional Collaboration',
  'Mentorship & Peer Guidance',
  'Team Player',
  'Stakeholder Management',
  // Thinking & Problem Solving
  'Problem Solving',
  'Critical Thinking',
  'Analytical Reasoning',
  'Creative Ideation',
  'Decision Making',
  'Root Cause Analysis',
  // Productivity & Management
  'Time Management',
  'Project Management',
  'Agile / Scrum Methodology',
  'Prioritization & Multitasking',
  'Goal Orientation',
  // Personal Traits & Work Ethic
  'Adaptability',
  'Fast Learner',
  'Resilience Under Pressure',
  'Attention to Detail',
  'Work Ethic & Ownership',
  'Conflict Resolution',
  'Emotional Intelligence',
  'Negotiation Skills',
];
