import { DriveWithCompany } from '../types/drive.types';
import { SEED_COMPANIES } from '../companies/queries';

export const SEED_DRIVES: DriveWithCompany[] = [
  {
    id: 'drive-msft-2026',
    company_id: 'c101-msft',
    job_role: 'Software Development Engineer (Cloud & AI)',
    package_details: '₹44.50 LPA (Base: ₹18.0 LPA + RSUs)',
    tier: 'Tier 1 (Super Dream)',
    location: 'Hyderabad / Bengaluru',
    description:
      'Microsoft India Development Center (IDC) is driving engineering innovations across Azure distributed cloud infrastructure, Office 365 services, Developer Tools, and Copilot AI systems. Selected engineers will architect high-concurrency microservices, distributed storage pipelines, and global-scale data platforms.',
    min_cgpa: 8.0,
    eligible_departments: [
      'Computer Science & Engineering',
      'Information Technology',
    ],
    eligible_years: [3, 4],
    max_backlogs: 0,
    required_skills: [
      'Data Structures & Algorithms',
      'TypeScript',
      'Distributed Systems',
      'Cloud Computing',
    ],
    recruitment_stages: [
      'Round 1: Online Technical Assessment (3 Algorithmic Problems on Codility - 90 mins)',
      'Round 2: System Architecture & Data Structures (Virtual Technical)',
      'Round 3: Concurrent Programming & Low-Level Design',
      'Round 4: Engineering Director Fitment & System Scale Evaluation',
    ],
    registration_deadline: '2026-11-20T23:59:59Z',
    drive_date: '2026-11-28T09:00:00Z',
    drive_time: '09:00 AM IST',
    venue: 'Virtual Teams Assessment & Microsoft IDC Hyderabad',
    instructions: [
      'Candidates must carry their verified Institutional ID card and two updated physical resumes.',
      'Ensure college grade reports through Semester 6 are verified on your student profile.',
      'Formal academic attire is strictly mandatory for all evaluation rounds.',
    ],
    required_documents: [
      'College ID Card',
      'Latest Official Grade Card',
      'Updated Resume (2 Copies)',
      'Government Photo ID',
    ],
    vacancies: '12 Positions',
    bond_period: 'No Service Bond',
    status: 'open',
    created_by: null,
    created_at: '2026-09-01T10:00:00Z',
    updated_at: '2026-09-10T12:00:00Z',
    company: SEED_COMPANIES[0],
  },
  {
    id: 'drive-tcs-2026',
    company_id: 'c102-tcs',
    job_role: 'Digital Software Engineer',
    package_details: '₹7.50 – ₹9.00 LPA + Incentives',
    tier: 'Core Recruiter',
    location: 'Bengaluru / Hyderabad / Pune / Chennai',
    description:
      'TCS Digital is the premier engineering division of Tata Consultancy Services, focusing on next-generation cloud architectures, AI solutions, distributed microservices, and enterprise applications for Fortune 500 partners globally.',
    min_cgpa: 7.0,
    eligible_departments: [
      'Computer Science & Engineering',
      'Information Technology',
      'Electronics & Communication',
      'Electrical & Electronics',
    ],
    eligible_years: [3, 4],
    max_backlogs: 0,
    required_skills: [
      'Data Structures & Algorithms',
      'Java / Python',
      'SQL Database Design',
      'Web Technologies',
    ],
    recruitment_stages: [
      'Round 1: National Qualifier Online Cognitive & Coding Assessment (TCS iON)',
      'Round 2: Technical Evaluation & Live Coding Interview (Virtual)',
      'Round 3: Managerial Assessment & HR Fitment Round',
    ],
    registration_deadline: '2026-11-15T23:59:59Z',
    drive_date: '2026-11-22T09:00:00Z',
    drive_time: '09:00 AM IST',
    venue: 'Campus Placement Labs A & B / Online Proctored',
    instructions: [
      'Candidates must carry verified college ID card and two updated physical resumes.',
      'Formal academic dress code is strictly mandatory during all on-campus stages.',
      'Maintain stable internet connectivity for the virtual technical stage.',
    ],
    required_documents: [
      'College ID Card',
      'Semester Mark Sheets',
      'Resume (2 Copies)',
      'Aadhaar / Government ID',
    ],
    vacancies: '45 Positions',
    bond_period: 'No Service Bond',
    status: 'open',
    created_by: null,
    created_at: '2026-09-02T10:00:00Z',
    updated_at: '2026-09-12T14:00:00Z',
    company: SEED_COMPANIES[1],
  },
  {
    id: 'drive-deloitte-2026',
    company_id: 'c103-deloitte',
    job_role: 'Technology Advisory Analyst',
    package_details: '₹8.10 – ₹12.80 LPA + Bonus',
    tier: 'Tier 1 (Dream)',
    location: 'Hyderabad / Bengaluru / Gurugram',
    description:
      'Deloitte Technology Advisory provides strategy, architecture, cybersecurity, and cloud migration services to premier global brands across finance, life sciences, healthcare, and public sector organizations.',
    min_cgpa: 7.5,
    eligible_departments: [
      'Computer Science & Engineering',
      'Information Technology',
      'Electronics & Communication',
      'Mechanical Engineering',
    ],
    eligible_years: [3, 4],
    max_backlogs: 0,
    required_skills: [
      'Analytical Problem Solving',
      'Python / SQL',
      'Cloud Fundamentals',
      'Data Structures & Algorithms',
    ],
    recruitment_stages: [
      'Round 1: Deloitte Aptitude, Verbal & Technical MCQ Screen',
      'Round 2: Group Case Study Discussion & Technical Presentation',
      'Round 3: Partner Leadership Interview',
    ],
    registration_deadline: '2026-11-25T18:00:00Z',
    drive_date: '2026-12-02T09:30:00Z',
    drive_time: '09:30 AM IST',
    venue: 'Deloitte Virtual Assessment Suite',
    instructions: [
      'Review the Deloitte Advisory candidate guide before the group discussion stage.',
      'Formal business attire required for the virtual partner round.',
    ],
    required_documents: [
      'College ID Card',
      'Latest Grade Sheet',
      'Updated Resume',
      'Government Photo ID',
    ],
    vacancies: '25 Positions',
    bond_period: 'None',
    status: 'open',
    created_by: null,
    created_at: '2026-09-05T11:00:00Z',
    updated_at: '2026-09-15T09:00:00Z',
    company: SEED_COMPANIES[2],
  },
  {
    id: 'drive-infy-2026',
    company_id: 'c104-infy',
    job_role: 'Specialist Programmer (Power Programmer)',
    package_details: '₹9.50 LPA + Relocation Allowance',
    tier: 'Core Recruiter',
    location: 'Bengaluru / Mysuru / Pune',
    description:
      'Specialist Programmers at Infosys work directly on cutting-edge digital transformation projects, AI algorithms, and mission-critical cloud migrations for international financial and industrial institutions.',
    min_cgpa: 7.2,
    eligible_departments: [
      'Computer Science & Engineering',
      'Information Technology',
      'Electronics & Communication',
      'Electrical & Electronics',
    ],
    eligible_years: [3, 4],
    max_backlogs: 1,
    required_skills: [
      'Object Oriented Programming',
      'Python / Java',
      'Data Structures & Algorithms',
      'Database Queries',
    ],
    recruitment_stages: [
      'Round 1: Infosys HackWithInfy / National Coding Assessment',
      'Round 2: Live Code Demonstration & System Review',
      'Round 3: Technical HR Evaluation',
    ],
    registration_deadline: '2026-12-01T23:59:59Z',
    drive_date: '2026-12-10T10:00:00Z',
    drive_time: '10:00 AM IST',
    venue: 'Auditorium Hall C & Computer Labs',
    instructions: [
      'Candidates must maintain accurate institutional contact numbers on their profile.',
      'Active verification from academic faculty advisor is required for hall ticket issuance.',
    ],
    required_documents: [
      'College ID Card',
      'Mark Sheets',
      'Resume (2 Copies)',
    ],
    vacancies: '30 Positions',
    bond_period: '1 Year Agreement',
    status: 'open',
    created_by: null,
    created_at: '2026-09-08T14:00:00Z',
    updated_at: '2026-09-16T11:00:00Z',
    company: SEED_COMPANIES[3],
  },
  {
    id: 'drive-cisco-2026',
    company_id: 'c106-cisco',
    job_role: 'Technical Consulting Engineer (Networking & Security)',
    package_details: '₹17.50 LPA (Base: ₹13.0 LPA + Benefits)',
    tier: 'Tier 1 (Dream)',
    location: 'Bengaluru',
    description:
      'Cisco Customer Experience engineering teams design, troubleshoot, and automate enterprise architectures, cybersecurity zero-trust platforms, and mission-critical cloud backbones worldwide.',
    min_cgpa: 7.8,
    eligible_departments: [
      'Computer Science & Engineering',
      'Information Technology',
      'Electronics & Communication',
    ],
    eligible_years: [3, 4],
    max_backlogs: 0,
    required_skills: [
      'Computer Networks',
      'Python',
      'Linux',
      'Cybersecurity Fundamentals',
    ],
    recruitment_stages: [
      'Round 1: Online Networking & Coding Test (90 mins)',
      'Round 2: Technical System Troubleshooting & Architecture',
      'Round 3: Leadership & Team Fitment Interview',
    ],
    registration_deadline: '2026-12-05T23:59:59Z',
    drive_date: '2026-12-14T09:30:00Z',
    drive_time: '09:30 AM IST',
    venue: 'Cisco Virtual Assessment & Bangalore Campus',
    instructions: [
      'Stable broadband connection and working webcam mandatory for all virtual stages.',
      'Formal academic attire required.',
    ],
    required_documents: [
      'College ID Card',
      'Official Transcripts',
      'Resume (PDF)',
    ],
    vacancies: '15 Positions',
    bond_period: 'None',
    status: 'open',
    created_by: null,
    created_at: '2026-09-10T09:00:00Z',
    updated_at: '2026-09-17T16:00:00Z',
    company: SEED_COMPANIES[5],
  },
];
